Feauture/dsg 1411/pubsub client
Nuvalence/dsgov-libs pull request #54
Opened 2023-10-13 14:16 UTC by jcsuarezm

2023-10-13 14:17 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/brokerclient/config/PubSubAutoConfiguration.java
> +    public void createTopicsAndSubscriptions(SubscriberProperties subscriberProperties) {
This was added for ease of use when running locally, but it can be removed if desired.

2023-10-13 14:19 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/event/TestEvent.java
> +public class TestEvent extends Event {
Simple concrete implementation of the Event class, just a place holder to show expected usage. This should be deleted when real concrete implementations are created.

2023-10-13 14:30 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/subscriber/PubSubEventSubscriber.java
> +                            message.ack();
This was added to prevent retries because these exceptions are not recoverable and trying again would yield the same result

2023-10-17 20:29 UTC, jgnuvalence requested changes

2023-10-17 20:29 UTC, jgnuvalence commented on dsgov-events/build.gradle
> +apply plugin: 'maven-publish'
is there a reason why you have this plugins here?, maven-publish is part of the parent gradle project, and I don't see the java one in any other module, is it needed for any particular reason?

2023-10-17 20:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/event/EventGetter.java
> +    ObjectMapper mapper = new ObjectMapper();
Maybe it would be good to create an ObjectMapper bean to inject it instead of creating it here?, and use it in other places where it is required in the lib

2023-10-17 20:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/event/EventGetter.java
> +        return mapper.readValue(data, eventType);
I think we should encapsulate JsonProcessingException in a try/catch and throw an EventProcessingException

2023-10-17 20:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/subscriber/PubSubEventSubscriber.java
> +    private final ObjectMapper objectMapper;
here you are injecting ObjectMapper from the spring context, I think the same can be done in EventGetter

2023-10-17 20:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/publisher/PubSubEventPublisher.java
> +    private final ObjectMapper objectMapper;
here you are injecting ObjectMapper from the spring context, I think the same can be done in EventGetter, however, would it be better to use Lombok instead of manually creating the constructor?

2023-10-17 21:39 UTC, jcsuarezm commented on dsgov-events/build.gradle
> +apply plugin: 'maven-publish'
Thanks Julián, this has been corrected.

2023-10-17 21:39 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/event/EventGetter.java
> +    ObjectMapper mapper = new ObjectMapper();
Thanks Julián, this is being injected now.

2023-10-17 21:44 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/event/EventGetter.java
> +        return mapper.readValue(data, eventType);
Thanks Julián, a try/catch was added.

2023-10-17 21:45 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/subscriber/PubSubEventSubscriber.java
> +    private final ObjectMapper objectMapper;
Thank you, EventGetter was corrected.

2023-10-17 21:46 UTC, jcsuarezm commented on dsgov-events/src/main/java/io/nuvalence/events/publisher/PubSubEventPublisher.java
> +    private final ObjectMapper objectMapper;
Thank you, the @RequiredArgsConstructor annotation is now in use.

2023-10-17 21:51 UTC, jgnuvalence approved these changes
LGTM

2023-10-17 21:52 UTC, merged