DSG-1412/dsgov-events-create-event-classes-for-the-Audit-events
Nuvalence/dsgov-libs pull request #65
Opened 2023-11-23 20:50 UTC by afcalderonm

2023-11-23 22:29 UTC, jgnuvalence requested changes
It looks great!, just a couple of minor comments

2023-11-23 22:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/event/AuditEvent.java
> +    private UUID eventId;
this is not necessary since event has the EventMetadata attribute, which already has an id

2023-11-23 22:29 UTC, jgnuvalence commented on dsgov-events/src/main/java/io/nuvalence/events/event/service/EventGetter.java
> +        eventTypes.put("auditEvents", AuditEvent.class);
Would auditEvent be better ? (in singular)

2023-11-24 16:04 UTC, afcalderonm commented on dsgov-events/src/main/java/io/nuvalence/events/event/AuditEvent.java
> +    private UUID eventId;
remove it

2023-11-24 16:04 UTC, afcalderonm commented on dsgov-events/src/main/java/io/nuvalence/events/event/service/EventGetter.java
> +        eventTypes.put("auditEvents", AuditEvent.class);
fixed

2023-11-24 16:17 UTC, jgnuvalence approved these changes

2023-11-24 16:18 UTC, jgnuvalence approved these changes

2023-11-24 16:20 UTC, merged