Chore/dsg 2647/sonarqube major
Nuvalence/dsgov-libs pull request #89
Opened 2024-02-02 14:35 UTC by mattspahr-nuv

2024-02-02 14:36 UTC, mattspahr-nuv commented on dsgov-auth/src/main/java/io/nuvalence/auth/access/cerbos/CerbosAuthFilter.java
> +            throw new DsgovRuntimeException("Index '" + index + "' is out-of-bounds.");
Fixes: `Define and throw a dedicated exception instead of using a generic one.`

2024-02-02 14:36 UTC, mattspahr-nuv commented on dsgov-auth/src/main/java/io/nuvalence/auth/token/firebase/FirebaseInitializer.java
> +            throw new DsgovRuntimeException(e);
Fixes: `Define and throw a dedicated exception instead of using a generic one.`

2024-02-02 14:36 UTC, mattspahr-nuv commented on dsgov-events/src/main/java/io/nuvalence/events/publisher/PubSubEventPublisher.java
> +            throw new DsgovRuntimeException(e);
Fixes: `Define and throw a dedicated exception instead of using a generic one.`

2024-02-02 14:37 UTC, mattspahr-nuv commented on dsgov-auth/src/main/java/io/nuvalence/auth/token/TokenFilter.java
> +    private Authentication attemptAuthentication(final HttpServletRequest request)
Fixes: ```Remove this unused method parameter "response".```

2024-02-02 15:08 UTC, JayStGelais requested changes

2024-02-02 15:08 UTC, JayStGelais commented on dsgov-auth/src/main/java/io/nuvalence/auth/token/UserRoleMapper.java
> +@UtilityClass
Reading the docs on `@UtilityClass` it does not appear that this is likely to be promoted out of experimental status as it has some known usability issues (regarding static * imports).

I think we should manually apply the utility class best practices here.

2024-02-02 15:08 UTC, JayStGelais commented on dsgov-auth/src/main/java/io/nuvalence/auth/token/firebase/FirebaseTokenRevoker.java
> +@UtilityClass
Same comment as above on `@UtilityClass`

2024-02-02 15:08 UTC, JayStGelais commented on dsgov-auth/src/main/java/io/nuvalence/auth/token/firebase/FirebaseTokenVerifier.java
> +@UtilityClass
Same comment as above on `@UtilityClass`

2024-02-02 15:08 UTC, JayStGelais commented on dsgov-events/src/main/java/io/nuvalence/events/event/enums/AuditEventType.java
> +@UtilityClass
Same comment as above on `@UtilityClass`

2024-02-08 21:47 UTC, JayStGelais approved these changes

2024-02-08 21:48 UTC, merged